server:
  port: 20000
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8333
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.10
    port: 6379
  session:
    store-type: redis
  zipkin:
    base-url: http://192.168.56.10:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug
