server:
  port: 9000

spring:
  application:
    name: gulimall-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8333
  rabbitmq:
    host: 192.168.56.10
    port: 5672
    virtual-host: /
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
    publisher-confirm-type: correlated
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.10
    port: 6379
  session:
    store-type: redis
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss
  zipkin:
    base-url: http://192.168.56.10:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug