server:
  port: 30001

spring:
  application:
    name: gulimall-cart
  thymeleaf:
    cache: false
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8333
  redis:
    host: 192.168.56.10
    port: 6379
  session:
    store-type: redis
  zipkin:
    base-url: http://192.168.56.10:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug
